package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloApp.idl
* Monday, 21 April, 2025 10:25:03 PM IST
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
