package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorApp.idl
* Monday, 21 April, 2025 11:27:20 PM IST
*/

public interface CalculatorOperations 
{
  int operation (int arg1, int arg2, String method);
} // interface CalculatorOperations
